jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

spring:
  datasource:
    url: jdbc:mysql://gradation.cti8yc6ycfbc.ap-northeast-2.rds.amazonaws.com/gradation?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: 1q2w3e4r!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

cloud:
  aws:
    s3:
      bucket: hh99-spring-lv5
    credentials:
      access-key: AKIAQSJ2TLL6C7CYXYCB
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

server:
  port: 8080

