jwt:
  secret:
    key: ${JWT.SECRET.KEY}
spring:
  datasource:
    url: jdbc:mysql://${RDS.HOSTNAME}:${RDS.PORT}/${RDS.DB.NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${RDS.USERNAME}
    password: ${RDS.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS.HOSTNAME}
      port: ${REDIS.PORT}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
cloud:
  aws:
    s3:
      bucket: ${S3.BUCKETNAME}
    credentials:
      access-key: ${S3.ACCESS.KEY}
      secret-key: ${S3.SECRET.KEY}
    region:
      static: ${S3.REGION}
      auto: false
    stack:
      auto: false
server:
  port: ${SERVER.PORT}